name: CI

on:
  push:
  release:
    types: [published]

jobs:
  build-skl-igpu:
    name: Build (Skylake)
    runs-on: macos-latest
    steps:
      - name: Build
        uses: actions/checkout@v3

      - run: mkdir Output && zip --exclude '*.git*' --exclude '*.github*' --exclude '*Output*' -r -X "Output/${{ github.event.repository.name }}-${{github.ref_name}}-Skylake.zip" .

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Output/*.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Output/*.zip
          tag: ${{ github.ref }}
          file_glob: true

  build-kbl-igpu:
    name: Build (Kaby Lake)
    runs-on: macos-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
      
      - run: plutil -remove "DeviceProperties"."Add"."PciRoot(0x0)/Pci(0x2,0x0)"."device-id" EFI/OC/config.plist
      - run: plutil -remove "DeviceProperties"."Add"."PciRoot(0x0)/Pci(0x2,0x0)"."framebuffer-fbmem" EFI/OC/config.plist
      - run: plutil -replace "NVRAM"."Add"."7C436110-AB2A-4BBB-A880-FE41995C9F82"."SystemProductName" -string MacBookPro14,3 EFI/OC/config.plist
      - run: plutil -replace "NVRAM"."Add"."7C436110-AB2A-4BBB-A880-FE41995C9F82"."boot-args" -string "-v keepsyms=1 debug=0x100" EFI/OC/config.plist
      - run: plutil -remove "Booter"."Patch" EFI/OC/config.plist
      - run: plutil -insert "Booter"."Patch" -xml "<array/>" EFI/OC/config.plist 
      - run: plutil -replace "IOKitPersonalities"."TBTU"."model" -string MacBookPro14,3 EFI/OC/Kexts/USBMap.kext/Contents/Info.plist
      - run: plutil -replace "IOKitPersonalities"."XHC"."model" -string MacBookPro14,3 EFI/OC/Kexts/USBMap.kext/Contents/Info.plist
      - run: mkdir Output && zip --exclude '*.git*' --exclude '*.github*' --exclude '*Output*' -r -X "Output/${{ github.event.repository.name }}-${{github.ref_name}}-Kaby-Lake.zip" .  

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Output/*.zip

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Output/*.zip
          tag: ${{ github.ref }}
          file_glob: true
